### ISSUE TITLE
wiki里面关于烧录的最关键的几张图片都无法显示

### ISSUE THREAD

**Issue by walk728** [a2633063/zM1#1]
as title

**Comment by liyiecho** [comment]
用/替换%5C就行了，比如https://github.com/a2633063/zM1/wiki/image%5Cemw3080.png ，用/替换后自动跳转到 https://raw.githubusercontent.com/wiki/a2633063/zM1/image/emw3080.png

**Comment by a2633063** [comment]
> 用/替换%5C就行了，比如https://github.com/a2633063/zM1/wiki/image%5Cemw3080.png ，用/替换后自动跳转到 https://raw.githubusercontent.com/wiki/a2633063/zM1/image/emw3080.png

谢谢
看到这个终于找到不显示的原因了,现在文档图片应该正常了,请关闭此问题
