### ISSUE TITLE
请问能否修改时区？

### ISSUE THREAD

**Issue by hotsnow** [a2633063/zM1#11]
不在国内使用，请问能否增加修改时区功能？谢谢。

**Comment by a2633063** [comment]
后期增加

**Comment by a2633063** [comment]
更新固件至v0.0.8版本 支持时区
不过app端还未更新此功能 请等待 app版本 v1.1.0

**Comment by a2633063** [comment]
app v1.1.0版本已经发布 请更新确认后 close issue

**Comment by hotsnow** [comment]
已经测试通过，谢谢
