### ISSUE TITLE
无法在APP里添加设备

### ISSUE THREAD

**Issue by xiehe1250** [a2633063/zM1#12]
点击添加设备-获取局域网设备，点击后无法获取新设备。请问如何解决。是因为我已经配对了两个M1了吗？不能再添加新的M1吗？

**Comment by a2633063** [comment]
可能udp广播不稳定导致无法收到数据, 可以多试几次
也可以将此M1恢复默认模式 用手机连接热点,在app中获取局域网设备,获取到设备后再在web中配网,
后续会改为mdns来发现设备 应该会比现在udp获取稳定
