### ISSUE TITLE
请问没有MQTT服务器能否通过app手动或者定时调节亮度？

### ISSUE THREAD

**Issue by houniaolu** [a2633063/zM1#13]
试了一下好像不行。谢谢！

**Comment by a2633063** [comment]
没有mqtt服务器的情况下 使用的是局域网udp广播通信,此方法不稳定,和你的网络环境有很大关系,
建议尽量使用mqtt服务器

**Comment by houniaolu** [comment]
好的，更新了1.10版apk后试过可以了。谢谢！
