### ISSUE TITLE
无法连接WiFi,指示灯和X呈暗色

### ISSUE THREAD

**Issue by ghost** [a2633063/zM1#14]
本来是HA劫持接入的，运行了差不多半年WiFi指示灯变暗了，但有的时候却能诈尸变亮正常连接上传数据。
最近连诈尸都做不到了，怀疑是哪里坏了，拆开刷机测试，刷完固件能到配网阶段。
网页输入WiFi信息后重启WiFi指示灯又会像未刷机一样变暗。

**Comment by ghost** [comment]
固件TTL口输出：（已从网页配网）（无法输入任何字符）
ROM:[V0.1]
FLASHRATE:4
BOOT TYPE:0 XTAL:40000000
IMG1 DATA[1128:10002000]
IMG1 ENTRY[800046f:100021ef]
[233][MOC MAIN: moc_main.c: 199] Lib version 3080B002.024. APP built time 17:48:14
[243][MOC MAIN: moc_main.c: 200] heap reuse from 0x1003101c, 57300 bytes
[251][RTOS: mico_rtos_common.c:  84] Started MiCO RTOS interface for mocOS v1.0.0
[259][M1: main.c:  78] Start v0.0.8

使用HA论坛的mqtt固件输出：（无法输入任何字符）（无法配网）
ROM:[V0.1]
FLASHRATE:4
BOOT TYPE:0 XTAL:40000000
IMG1 DATA[1128:10002000]
IMG1 ENTRY[800046f:100021ef]
[233][MOC MAIN: moc_main.c: 199] Lib version 3080B002.024. APP built time 17:48:14
[243][MOC MAIN: moc_main.c: 200] heap reuse from 0x1003101c, 57300 bytes
[251][RTOS: mico_rtos_common.c:  84] Started MiCO RTOS interface for mocOS v1.0.0

**Comment by a2633063** [comment]
不明白你说的变暗是什么意思...
能否拍照上传
网页输入WiFi信息后重启wifi,wifi led闪烁表示正在连接wifi
如果连接失败wifi和红色叉led都会恒亮.
wifi的led亮度和屏幕有关  若关闭屏幕 wifiled会以非常低的亮度点亮

**Comment by ghost** [comment]
![IMG_20200414_142156](https://user-images.githubusercontent.com/19420642/79192486-60d64400-7e5b-11ea-8e87-6dea8ac5b456.jpg)

**Comment by ghost** [comment]
配网完成后重启指示灯就会变暗。开关屏幕等都无变化.
按15s全屏幕会点亮，但WIFI指示灯和红X不会变亮，也无法重新配网.
通电开机WiFi LED不会闪烁，直接呈现暗色。红X也一样

Bootloader 下  输入qc可以搜索到WIFI 连接成功并且获取到ip，所以我现在也搞不懂是不是坏了什么的。
      MXCHIP> qc

Boot QC
==== MXCHIP Manufacture Test ====
Serial Number: 0000.0000.0004
App CRC: 2DDD
PID: MICO_TEST_PID
Bootloader Version: EMW3080B v3.4 921600
Library Version: 3080B002.024
APP Version: ZYC_BASIC_1_0
Driver: 3080B-3.6a
result 0, num 4
MAC: ***
SDS: 

      Scan AP Success:
  SSID: 123123, RSSI: -42
  SSID: ***, RSSI: -51
  SSID: ***, RSSI: -65

Please input as "ssid <ssid_string>"
MXCHIP_MFMODE> ssid 123123
AP Connect Success
DHCP Get IP Success, IP address: 192.168.43.222
DHCP Get IP Success, IP address: 192.168.43.222

**Comment by ghost** [comment]
Jlink，TTL刷机后同样结果，感觉是模块损坏。
不折腾M1了，以后有时间不如做一个检测器。
