### ISSUE TITLE
断电问题。

### ISSUE THREAD

**Issue by MSquach** [a2633063/zM1#16]
每次断电来电后，屏幕都会恢复最亮，而且你的定时计划失效了。

**Comment by a2633063** [comment]
断电来电后，屏幕都会恢复最亮 就是这么设计的..
定时计划失效是指重启后失效吗  还是概率性失效 还是完全没反应

**Comment by 1005789164** [comment]
> 断电来电后，屏幕都会恢复最亮 就是这么设计的..
> 定时计划失效是指重启后失效吗 还是概率性失效 还是完全没反应

**Comment by MSquach** [comment]
> 断电来电后，屏幕都会恢复最亮 就是这么设计的..
> 定时计划失效是指重启后失效吗 还是概率性失效 还是完全没反应

在APP里重启后定时任务都是正常的。
强制断电通电后，定时任务全部失效。至于是不是概率性的我不清楚，目前只要是强制断电定时任务都会失效。目前还没有出现没有失效的。

**Comment by a2633063** [comment]
强制断电通电后,需要等待校时成功定时任务才有效.
另外如果定时的时间m1为断电状态,定时任务当然无效
