### ISSUE TITLE
请求你的帮助

### ISSUE THREAD

**Issue by GWan1234** [a2633063/zM1#18]
很感谢你的开源固件，我的设备正常使用，目前想要通过HB接入温度到Homebridge Mqtt Acpartner的空调卡片，无奈尝试无果，特来寻求帮助，

>         {
            "accessory": "acpartner",
            "name": "空调",
            "serviceType": "HeaterCooler",
            "mqtttemp": "device/zm1/b0f8931e283b/set",
            "mqtt": {
                "server": "192.168.124.25:1883",
                "prefix": "irmqtt186d24",
                "username": "king",
                "password": "admin"
            }
        },
这是我的HB配置，在温度那一行，我无法正确写入，请求您的指点。

**Comment by a2633063** [comment]
我没用过hb  帮不上你了 
不过获取温度的topic应该是 device/zm1/b0f8931e283b/state

**Comment by GWan1234** [comment]
好的，谢谢！
