### ISSUE TITLE
刷机后屏显wifi没了,也找不到zm1开头的wifi

### ISSUE THREAD

**Issue by leadlxx** [a2633063/zM1#21]
使用JLINK刷机,看日志应该是刷成功了,但是wifi没了
========================dest_address_loc= 507904
target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x61000000 pc: 0x1000b8ca msp: 0x1003efc4
****************** Result: OK
target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x61000000 pc: 0x1000b8ca msp: 0x1003efc4
target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x61000000 pc: 0x1000b8c8 msp: 0x1003efc4
****************** Result: OK
Warn : Only resetting the Cortex-M core, use a reset-init event handler to reset any peripherals or configure hardware srst support.
target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x00000100 msp: 0x1003effc
Warn : Only resetting the Cortex-M core, use a reset-init event handler to reset any peripherals or configure hardware srst support.
target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x00000100 msp: 0x1003effc
40824 bytes written at address 0x10005000
downloaded 40824 bytes in 0.742491s (53.694 KiB/s)
entry_address= 268483069
stack_address= 268693500
buffer_size= 16384
pc (/32): 0x1000B9FD
sp (/32): 0x1003EFFC
Total write size is 0 to partition 3
target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x61000000 pc: 0x1000b8c8 msp: 0x1003efc4
target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x61000000 pc: 0x1000b972 msp: 0x1003efc4
****************** Result: OK
Warn : Only resetting the Cortex-M core, use a reset-init event handler to reset any peripherals or configure hardware srst support.
shutdown command invoked 
![图片](https://user-images.githubusercontent.com/48824914/90951089-0a70b600-e48a-11ea-8919-be50c713b018.png)

![图片](https://user-images.githubusercontent.com/48824914/90951105-23796700-e48a-11ea-8f6c-061cb2e33c3e.png)

**Comment by mmkkllpp** [comment]
同样的问题，楼主搞定了吗，我的也是刷机找不到热点，WiFi图标也不亮，烧录窗口不是一闪而过，应该是刷成功的

**Comment by a2633063** [comment]
重刷  确认固件放入正确

**Comment by mmkkllpp** [comment]
我搞定了，不要刷最新版，最新版只有ota固件，不是完整的

**Comment by a2633063** [comment]
> 我搞定了，不要刷最新版，最新版只有ota固件，不是完整的

最新版本已经补充all.bin文件供线刷.

注意:请仔细查看文档确认刷机文件的使用

**Comment by leadlxx** [comment]
用all.bin文件就可以刷新,已成功接入到HA
