### ISSUE TITLE
pm2.5的颜色变化能否改成美标的？

### ISSUE THREAD

**Issue by theosoft-git** [a2633063/zM1#24]
m1默认的国标的，75才会变黄。
能否改成美标，到35就变成黄色。
参考：http://www.pm25.com/news/96.html

**Comment by a2633063** [comment]
本固件仅实现将数据联网发送功能
屏幕上显示的数据为原厂实现,未做任何修改.(因此屏幕显示的值/效果/精度都为原厂实现,与本固件无关)
