### ISSUE TITLE
无法设置mqtt服务器  

### ISSUE THREAD

**Issue by ZJDATY** [a2633063/zM1#29]
之前刷完机，用过mqtt，配置方法也清楚明白，后来用的mqtt服务器关闭了。重新配置了一个无需登录名和密码的服务器，app上提示app已连接到mqtt服务器。也点了云朵进行了上报，app界面上已出现“已设置“zM1..服务器...”。这说明已经上报成功了啊 ，但我用mqtt一直看不了信息，只能通过udp。之前看了重新配置mqtt需要手动重启。我也重新上电了啊 。为什么就是用不了呢。会是空用户名和密码的原因吗，但我身边也没有别的mqtt服务器了 ，没法测试。希望能查一下这个问题。

**Comment by a2633063** [comment]
未测试过无密码的mqtt服务器 可以加个密码测试下
我后面测试

**Comment by ZJDATY** [comment]
> 未测试过无密码的mqtt服务器 可以加个密码测试下
> 我后面测试

我又找了个带密码的测试了   可以用  问题就出在空用户名和密码上  app能连上  但是无法上报到设备里

**Comment by a2633063** [comment]
不考虑不带密码的mqtt服务器 关闭此问题
