### ISSUE TITLE
整体灯光亮度问题

### ISSUE THREAD

**Issue by nxcjs** [a2633063/zM1#3]
wifi灯不能关闭，原厂固件是可以关闭的，界面灯不能调到最亮，只有wifi灯可以

**Comment by nxcjs** [comment]
这个最亮指的是比wifi灯暗，我记得原厂的灯是一样亮的

**Comment by a2633063** [comment]
屏幕熄灭时 为了区分未上电和熄屏 设计成息屏时wifi灯最暗点亮
除了wifi灯外 其他显示亮度为原厂配置 未做修改  可能wifi灯亮度和原厂不同  确实可以调整为完全相同亮度   亮度调整需要参数依次测试 意义不大了  亮度后续应该不会专门去调节

**Comment by nxcjs** [comment]
感觉屏幕最大亮度还是太暗，白天看上去有点吃力

**Comment by nxcjs** [comment]
后期如果有空的话，可以加亮一点
