### ISSUE TITLE
zm1亮度自己會啟動，ha log出現錯誤訊息。

### ISSUE THREAD

**Issue by charles0103** [a2633063/zM1#30]
最近發現ha偶爾會有錯誤訊息出現如下：
Logger: homeassistant.components.mqtt.light.schema_template
Source: components/mqtt/light/schema_template.py:187
Integration: MQTT (documentation, issues)
First occurred: 上午12:18:29 (6 occurrences)
Last logged: 下午12:35:20

Invalid brightness value received
---------------------------------------------------------------------------------
不知道是哪裡有設定錯誤呢？

**Comment by a2633063** [comment]
可以忽略 这个是因为mqtt的数据中不包含brightness 字段
m1只有在请求亮度屏幕开关时才会返回此brightness 字段的数据   否则不会带brightness 字段.
ha监测到收到数据但是读不到brightness 字段时就会出现此警告信息. 可以屏蔽此内容.
只有在使用app来设置m1定时/设置功能时才会出现此问题 可以忽略

**Comment by charles0103** [comment]
謝謝！了解！
