### ISSUE TITLE
能否使用ST-LINK代替J-LINK进行刷机？

### ISSUE THREAD

**Issue by Jackadminx** [a2633063/zM1#31]
用CH340无法尝试进入BootLoader失败，暂时没有J-LINK请问能否使用ST-LINK进行刷机

**Comment by a2633063** [comment]
根据wifi模组的官方信息,是可以通过ST-LINK烧录的
但是此仅对于开发过程中使用开发工具直接烧录.
你可以参考当前jlink的烧录脚本 修改脚本内容实现stlink烧录

官方文档可以参考http://developer.mxchip.com/handbooks/103

**Comment by Jackadminx** [comment]
谢谢，这边找到J-LINK把固件刷进去了😂
