### ISSUE TITLE
连接SecureCRT乱码问题

### ISSUE THREAD

**Issue by stockzhangchao** [a2633063/zM1#38]
连接9，10，17，19线时，16未通电，屏幕乱码。16通电后连接断开。
16未通电，19线未连接时，屏幕无变化，19一接触触点就出现乱码，大神求解！
![image](https://user-images.githubusercontent.com/54971232/160636962-99ba5326-9bf6-4a5b-9f5a-69c784589b81.png)

![image](https://user-images.githubusercontent.com/54971232/160636820-c184e3c2-749c-456d-856e-0bb3cf8cd081.png)

**Comment by a2633063** [comment]
wifi模组与mcu主控也通过此串口通信   因此若正好此时有通信 此处就会有乱码   这也是部分刷机时刷一部分失败的原因
另外也可能是你接线有问题/接触不良等问题   需要你自行排除问题
建议使用jlink刷成功率会高很多

**Comment by a2633063** [comment]
重复,详情见 #50
