### ISSUE TITLE
ota升级问题

### ISSUE THREAD

**Issue by guitengyue** [a2633063/zM1#42]
目前刷的是V0.1.3
WIN PC控制器点击更新获取状态，只输出这么一条：
[9:53:08][] :{	"mac":	"b0f893254258",	"version":	"v0.1.3",	"brightness":	4,	"name":	"zM1_4258"}
然后就没了？我看了下最新是v0.1.4了呀？还是只能通过安卓的app进行升级？

**Comment by a2633063** [comment]
> 目前刷的是V0.1.3
> WIN PC控制器点击更新获取状态，只输出这么一条：
> [9:53:08][] :{	"mac":	"b0f893254258",	"version":	"v0.1.3",	"brightness":	4,	"name":	"zM1_4258"}
> 然后就没了？我看了下最新是v0.1.4了呀？还是只能通过安卓的app进行升级？

这是当前设备版本 升级请使用app
