### ISSUE TITLE
请教下如何设置M1 的时区？

### ISSUE THREAD

**Issue by holywen** [a2633063/zM1#43]
Release里面看到0.0.8里面就已经支持时区了，但是不知道如何设置呢？

**Comment by holywen** [comment]
搞定了：
mosquitto_pub -h 192.168.1.X -u mqtt -P mqtt -t "device/zm1/MAC/set" -m '{ "name":"zM1_XXXX","mac":"MAC","zone":420}'

**Comment by holywen** [comment]
MAC替换成全小写的mac地址，zM1_XXXX替换成设备的名字，-u -P 是mqtt的用户名和密码

**Comment by men9xuan** [comment]
> 搞定了： mosquitto_pub -h 192.168.1.X -u mqtt -P mqtt -t "device/zm1/MAC/set" -m '{ "name":"zM1_XXXX","mac":"MAC","zone":420}'

你好 请问这里的ip是m1的ip地址还是MQTT服务器地址
