### ISSUE TITLE
波特率不匹配

### ISSUE THREAD

**Issue by paopaoqaini** [a2633063/zM1#47]
老大 我的电脑串口波特率只能到128000 但是CRT要921600，CRT能读取到所有的数据 就是没办法command 光标闪烁 请指导下

**Comment by John-zhan** [comment]
你搞得定没有

**Comment by paopaoqaini** [comment]
搞定了  我换了  不ttl啦

**Comment by John-zhan** [comment]
ttl 这个你115200 试过没，我现在115200 串口就两个字符，"#!"

**Comment by paopaoqaini** [comment]
忘记啦  有点久了哦  我现在在外面吃饭

**Comment by a2633063** [comment]
更新软件,非刷机问题,关闭问题[](url)
