### ISSUE TITLE
大佬有兴趣搞新的机器吗

### ISSUE THREAD

**Issue by ghsssss** [a2633063/zM1#49]
https://iot.10086.cn/product/read/id/887
 咸鱼卖80，支持sim卡，支持甲醛，tvoc，pm2.5，温湿度，锂电池

**Comment by ghsssss** [comment]
![d477b30134757a92cc692e620ceee005](https://user-images.githubusercontent.com/25170955/230817402-b815d13d-2f04-49b1-8ccc-147ec54793f8.png)
而且可以当闹钟！

**Comment by a2633063** [comment]
简单搜了下  没找到拆机图  想先看下什么方案  
另外这种不打算再买了 如果有拆机图确认能做 如果有人送😏可以考虑开发接入zControl系统(mqtt)
