### ISSUE TITLE
建议增加设置mqtt数据上传频率的功能

### ISSUE THREAD

**Issue by maxmib** [a2633063/zM1#5]
建议增加设置mqtt数据上传频率的功能

**Comment by mzfe** [comment]
数据量太大了。

**Comment by maxmib** [comment]
反馈一下，0.7版本固件app通过udp与已设置了mqtt的设备通信时设置mqtt上传间隔会失效，如果默认值变成0就不会上传数据，要清空设备mqtt数据后重新发现设备设置好上传间隔再给设备配置mqtt信息（这个上传间隔的设置对于udp传送数据也是有效的）。

**Comment by maxmib** [comment]
发现一个新的问题，设备的上传间隔关机重启后不能保存，一直是第一次局域网发现设备后设定的值

**Comment by a2633063** [comment]
https://github.com/a2633063/zM1/issues/9
处理此问题

**Comment by maxmib** [comment]
建议增加开机联网后自动进行一次网络对时或者添加设置对时频率的功能，有时候重新通电后时间会快1到2分钟
