### ISSUE TITLE
是否可以通过MQTT Discovery在Home Assistant中把实体组合成一个设备

### ISSUE THREAD

**Issue by scythk** [a2633063/zM1#52]
阅读了一下home assistant的文档，可以通过配置MQTT Discovery的格式实现自动发现设备，通过设备的形式可以更直观的管理m1的实体同时降低配置的复杂度。
请问是否可以实现呢？
[MQTT Discovery](https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery)

**Comment by a2633063** [comment]
19年尝试使用此功能实现增加ha设备,但是发现部分配置不支持mqtt发现配置,所以只能关闭了此功能,目前若ha更新支持配置了,后续会考虑自动发现功能.
暂时关闭此issue,后续若发现可以再考虑更新固件实现
