### ISSUE TITLE
局域网udp通信时在app里信息显示的问题

### ISSUE THREAD

**Issue by maxmib** [a2633063/zM1#7]
当有多个m1的时候，app里设置了mqtt，只有设置了相同mqtt信息的m1设备的数据可以正常显示，局域网内没有配置mqtt的m1就算设置始终udp通信在app里也不能显示数据，只能显示屏幕亮度的信息

**Comment by maxmib** [comment]
m1固件版本0.7，安卓app版本0.13.3，使用手机小米8，安卓10

**Comment by a2633063** [comment]
没有配置mqtt的m1的传感器数据也使用udp广播发出
可以抓一下10181端口的udp包 看是否有数据
局域网udp广播通信不稳定 建议使用mqtt
